### ISSUE TITLE
binary blobs that are not verifiable

### ISSUE THREAD

**Issue by jumoog** [intro-skipper/jellyfin-androidtv#9]
Like I said, the **commit of the release** which links to https://github.com/intro-skipper/jellyfin-androidtv/commit/da4ce28b66bead099df97a0cf6a46db3d14dceb7. You're putting up binary blobs that are not verifiable.

_Originally posted by @nielsvanvelzen in https://github.com/intro-skipper/intro-skipper/issues/325#issuecomment-2395544213_

**Comment by jumoog** [comment]
> Like I said, the **commit of the release** which links to [intro-skipper/jellyfin-androidtv@da4ce28](https://github.com/intro-skipper/jellyfin-androidtv/commit/da4ce28b66bead099df97a0cf6a46db3d14dceb7). You're putting up binary blobs that are not verifiable.



> > Like I said, the **commit of the release** which links to [intro-skipper/jellyfin-androidtv@da4ce28](https://github.com/intro-skipper/jellyfin-androidtv/commit/da4ce28b66bead099df97a0cf6a46db3d14dceb7). You're putting up binary blobs that are not verifiable.
> 
> Actually, that's an inaccurate assumption. What happened is that the GitHub action modified the release binary, but not the release details due to an overlapping tag. A force push disconnected the hash listed from the hash of the actual commit.
> 
> I'm fixing the issue. Thanks for reporting it.

**Comment by jumoog** [comment]
Sorry issue where off and I couldnt move it

**Comment by AbandonedCart** [comment]
The softprops release action goes in a couple different directions. Apparently it amends the release, replaces the body, but leaves the original commit. So much for not needing to generate a bunch of tags...

**Comment by AbandonedCart** [comment]
Seems to be working now. 

@nielsvanvelzen You may want to confirm on your end just to be sure.

**Comment by nielsvanvelzen** [comment]
Looks like the release now links to a valid commit. Thanks for picking it up that quickly!

As a sidenote; it does look like you're basing the releases on our master branch, which is always the development branch for the next release (0.18 in this case). I'd recommend using our release-xxx branches instead as those are stable. Our current master branch contains multiple known issues with playback (mostly related to recent subtitle changes).

**Comment by AbandonedCart** [comment]
> Looks like the release now links to a valid commit. Thanks for picking it up that quickly!
> 
> As a sidenote; it does look like you're basing the releases on our master branch, which is always the development branch for the next release (0.18 in this case). I'd recommend using our release-xxx branches instead as those are stable. Our current master branch contains multiple known issues with playback (mostly related to recent subtitle changes).

I don't typically use the softprops action and my tags are usually the hash, but now I'll have to see if they are aware of that issue.

This really isn't a long-term solution. It was a temporary stop-gap because @brewkunz threw together a way to get the button working and we offered to host it. I can rebase it for archival purposes, but there are no real plans to maintain it once 10.10 is released.

ExoPlayer 1.4.0 made subtitles fun for everyone.
